// ============================================================
// lib/county-lookup.ts
//
// FIPS ↔ county name / slug conversion utilities.
//
// Data source: data/config/county-names.json (generated by
//   scripts/etl/build_county_names.py from CMS Service Area PUF)
//
// If county-names.json has not been generated yet, all functions
// fall back gracefully so pages still render (just without friendly names).
// ============================================================

import countyNamesRaw from '@/data/config/county-names.json'

// Maps 5-digit FIPS → county name (without "County" suffix)
// e.g. "37183" → "Wake",  "48201" → "Harris"
const fipsToName: Record<string, string> = countyNamesRaw as Record<string, string>

// Maps "wake-nc" (slug-state) → FIPS — built lazily
let slugToFips: Map<string, string> | null = null

function loadLookup(): Record<string, string> {
  return fipsToName
}

/** Maps 5-digit state FIPS prefix → 2-letter state code */
const STATE_FIPS_TO_CODE: Record<string, string> = {
  '01': 'AL', '02': 'AK', '04': 'AZ', '05': 'AR', '06': 'CA',
  '08': 'CO', '09': 'CT', '10': 'DE', '12': 'FL', '13': 'GA',
  '15': 'HI', '16': 'ID', '17': 'IL', '18': 'IN', '19': 'IA',
  '20': 'KS', '21': 'KY', '22': 'LA', '23': 'ME', '24': 'MD',
  '25': 'MA', '26': 'MI', '27': 'MN', '28': 'MS', '29': 'MO',
  '30': 'MT', '31': 'NE', '32': 'NV', '33': 'NH', '34': 'NJ',
  '35': 'NM', '36': 'NY', '37': 'NC', '38': 'ND', '39': 'OH',
  '40': 'OK', '41': 'OR', '42': 'PA', '44': 'RI', '45': 'SC',
  '46': 'SD', '47': 'TN', '48': 'TX', '49': 'UT', '50': 'VT',
  '51': 'VA', '53': 'WA', '54': 'WV', '55': 'WI', '56': 'WY',
}

/** Returns 2-letter state code for a 5-digit county FIPS, e.g. "37183" → "NC" */
export function getStateCodeFromFips(fips: string): string | null {
  const prefix = fips.slice(0, 2)
  return STATE_FIPS_TO_CODE[prefix] ?? null
}

/**
 * Returns the consumer-facing county name for a 5-digit FIPS code.
 * e.g. "37183" → "Wake County"
 *
 * If the lookup file is unavailable the function returns null rather than
 * exposing raw FIPS codes or machine-like labels in the public UI.
 * Callers must guard against null and either notFound() or show an error.
 */
export function getCountyName(fips: string): string | null {
  const lookup = loadLookup()
  const base = lookup[fips]
  if (base) return `${base} County`
  return null
}

/**
 * Same as getCountyName but throws if the name cannot be resolved.
 * Use this in contexts where a missing county name is a hard error.
 */
export function requireCountyName(fips: string): string {
  const name = getCountyName(fips)
  if (!name) throw new Error(`County name not found for FIPS ${fips}`)
  return name
}

/**
 * Returns the county base name (no "County" suffix) for use in titles/slugs.
 * e.g. "37183" → "Wake"
 */
export function getCountyBaseName(fips: string): string {
  const lookup = loadLookup()
  return lookup[fips] ?? fips
}

/**
 * Converts a county name to a URL slug.
 * "Wake County" → "wake-county"
 * "Harris" → "harris-county"
 */
export function countyNameToSlug(name: string): string {
  const clean = name.toLowerCase().replace(/\s+county$/i, '').trim()
  return `${clean.replace(/\s+/g, '-')}-county`
}

/**
 * Converts a county slug back to a display name.
 * "wake-county" → "Wake County"
 * "harris-county" → "Harris County"
 */
export function countySlugToName(slug: string): string {
  return slug
    .split('-')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ')
}

/**
 * Looks up the FIPS code for a county slug + state code combination.
 * "wake-county" + "NC" → "37183"
 * Returns null if not found (lookup file not generated yet).
 */
export function getFipsFromSlug(countySlug: string, stateCode: string): string | null {
  const lookup = loadLookup()

  if (!slugToFips) {
    slugToFips = new Map<string, string>()
    for (const [fips, base] of Object.entries(lookup)) {
      const sc = getStateCodeFromFips(fips)
      if (!sc) continue
      const slug = countyNameToSlug(base)
      slugToFips.set(`${slug}-${sc.toLowerCase()}`, fips)
    }
  }

  const key = `${countySlug}-${stateCode.toLowerCase()}`
  return slugToFips.get(key) ?? null
}

/**
 * Returns the canonical county slug for a FIPS code.
 * "37183" → "wake-county"
 */
export function getCountySlug(fips: string): string {
  const base = getCountyBaseName(fips)
  if (base === fips) return `county-${fips}` // fallback
  return countyNameToSlug(base)
}

/**
 * Full state name lookup for display in subheadlines.
 */
const STATE_NAMES: Record<string, string> = {
  AL: 'Alabama', AK: 'Alaska', AZ: 'Arizona', AR: 'Arkansas', CA: 'California',
  CO: 'Colorado', CT: 'Connecticut', DE: 'Delaware', FL: 'Florida', GA: 'Georgia',
  HI: 'Hawaii', ID: 'Idaho', IL: 'Illinois', IN: 'Indiana', IA: 'Iowa',
  KS: 'Kansas', KY: 'Kentucky', LA: 'Louisiana', ME: 'Maine', MD: 'Maryland',
  MA: 'Massachusetts', MI: 'Michigan', MN: 'Minnesota', MS: 'Mississippi', MO: 'Missouri',
  MT: 'Montana', NE: 'Nebraska', NV: 'Nevada', NH: 'New Hampshire', NJ: 'New Jersey',
  NM: 'New Mexico', NY: 'New York', NC: 'North Carolina', ND: 'North Dakota', OH: 'Ohio',
  OK: 'Oklahoma', OR: 'Oregon', PA: 'Pennsylvania', RI: 'Rhode Island', SC: 'South Carolina',
  SD: 'South Dakota', TN: 'Tennessee', TX: 'Texas', UT: 'Utah', VT: 'Vermont',
  VA: 'Virginia', WA: 'Washington', WV: 'West Virginia', WI: 'Wisconsin', WY: 'Wyoming',
  DC: 'District of Columbia',
}

export function getStateName(stateCode: string): string {
  return STATE_NAMES[stateCode.toUpperCase()] ?? stateCode.toUpperCase()
}

/**
 * Converts a state name to a URL slug.
 * "North Carolina" → "north-carolina"
 */
export function stateNameToSlug(stateName: string): string {
  return stateName.toLowerCase().replace(/\s+/g, '-')
}

/**
 * Converts a 2-letter state code to a URL slug.
 * "NC" → "north-carolina"
 */
export function stateCodeToSlug(stateCode: string): string {
  const name = STATE_NAMES[stateCode.toUpperCase()]
  return name ? stateNameToSlug(name) : stateCode.toLowerCase()
}

// Inverted map: slug → state code (built once at module load)
const STATE_SLUG_TO_CODE: Record<string, string> = {}
for (const [code, name] of Object.entries(STATE_NAMES)) {
  STATE_SLUG_TO_CODE[stateNameToSlug(name)] = code
}

/**
 * Converts a state slug back to a 2-letter state code.
 * "north-carolina" → "NC"
 * Returns null if not recognized.
 */
export function stateSlugToCode(slug: string): string | null {
  return STATE_SLUG_TO_CODE[slug.toLowerCase()] ?? null
}
